### ISSUE TITLE
http.client.IncompleteRead: IncompleteRead

### ISSUE THREAD

**Issue by dayhost** [mtth/hdfs#119]
I try to use 
`InsecureClient.download()` 
to download file from HDFS. 
However, I get an `IncompleteRead` error. 
The traceback log is
`Traceback (most recent call last):
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 601, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 566, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/Users/shuyuyin/anaconda3/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(27438 bytes read, 5330 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/Users/shuyuyin/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(27438 bytes read, 5330 more expected)', IncompleteRead(27438 bytes read, 5330 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shuyuyin/Desktop/git_code/for_hive_data_immgration/dump_files.py", line 47, in <module>
    dump_table_files(HDFS_CLIENT, FILE_PATH, CURRENT_PATH + "/data")
  File "/Users/shuyuyin/Desktop/git_code/for_hive_data_immgration/dump_files.py", line 14, in dump_table_files
    hdfs_client.download(hdfs_path=hdfs_file_path, local_path=data_dir_path + "/" + file_name, n_threads=0)
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/hdfs/client.py", line 817, in download
    raise err
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/hdfs/client.py", line 804, in download
    _download(fpath_tuple)
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/hdfs/client.py", line 747, in _download
    for chunk in reader:
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/requests/utils.py", line 435, in stream_decode_response_unicode
    for item in iterator:
  File "/Users/shuyuyin/anaconda3/lib/python3.6/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(27438 bytes read, 5330 more expected)', IncompleteRead(27438 bytes read, 5330 more expected))`

**Comment by mtth** [comment]
It's hard to say for sure from the stack trace but it looks like a connection issue. Are you able to download files via other means (e.g. `curl` or another client library)?
