### ISSUE TITLE
How to use kerberos client

### ISSUE THREAD

**Issue by anancds** [mtth/hdfs#120]
I refer to the document [https://hdfscli.readthedocs.io/en/latest/api.html#kerberos-extension](https://hdfscli.readthedocs.io/en/latest/api.html#kerberos-extension) but still don't kown how to use kerberos client. I have read the issue #82 #15 #58 #42 ,but it didn't work for me. My steps are as follows

1、
```
[root@dlssingle ~]# klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: hdfs@HADOOP.COM

Valid starting       Expires              Service principal
04/07/2019 23:25:11  04/08/2019 23:25:04  krbtgt/HADOOP.COM@HADOOP.COM
04/07/2019 23:50:06  04/08/2019 23:25:04  HTTP/*********@HADOOP.COM
```

2、the code is as followed
```
from hdfs.ext.kerberos import KerberosClient
import requests

session = requests.Session()
session.verify = False
client = KerberosClient('https://********:25003', session = session, principal = 'hdfs@HADOOP.COM', mutual_auth = 'OPTIONAL')

client.list('/')

```

3、The above code error is as follows

```
>>> client.list('/')
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 1008, in list
    statuses = self._list_status(hdfs_path).json()['FileStatuses']['FileStatus']
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 115, in api_handler
    err = _to_error(res)
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 39, in _to_error
    raise HdfsError('Authentication failure. Check your credentials.')
hdfs.util.HdfsError: Authentication failure. Check your credentials.


```

**Comment by mtth** [comment]
Hi @anancds. Two quick questions:

+ What happens if you omit the `session` (in particular the `verify = False`) and the principal (it looks like it's the default anyway)?
+ Can you enable logging and share the output here? Adding something like this at the top of a script should do the trick (`hdfscli --log` will show you where the log file is):

  ```python
  import logging
  logging.basicConfig(level=logging.DEBUG)
  ```
