### ISSUE TITLE
use bzip2 write to hdfs, Remote end closed connection without response

### ISSUE THREAD

**Issue by whg517** [mtth/hdfs#122]
The following error occurs when I write to HDFS using bzip2. The same error occurs with gzip. But it's okay to write text.

```python
import json
import bz2

from hdfs.ext.kerberos import KerberosClient

client = KerberosClient('http://m1.node.hadoop:50070')

# print(client.list(''))

redords = [
    {'name': 'foo', 'weight': 1},
    {'name': 'bar', 'weight': 2}
]

with client.write('t.bzip2', overwrite=True) as hdfs_writer:
    with bz2.open(filename=hdfs_writer, mode='w') as bzip2_writer:
        bzip2_writer.write(json.dumps(redords).encode('utf-8'))
```

```
Traceback (most recent call last):
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/requests/adapters.py", line 479, in send
    r = low_conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/requests/adapters.py", line 482, in send
    r = low_conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin/PycharmProjects/bigdata/trans/demo.py", line 17, in <module>
    bzip2_writer.write(json.dumps(redords).encode('utf-8'))
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/hdfs/util.py", line 101, in __exit__
    raise self._err # pylint: disable=raising-bad-type
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/hdfs/util.py", line 73, in consumer
    self._consumer(data)
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/hdfs/client.py", line 469, in consumer
    data=(c.encode(encoding) for c in _data) if encoding else _data,
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/hdfs/client.py", line 214, in _request
    **kwargs
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/kevin/.virtualenvs/bigdata-DVVGZu6O/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: Remote end closed connection without response

```

Is my operation mode incorrect, or what problem? The output from the console doesn't show much useful information.

Thank you for helping me.

**Comment by mtth** [comment]
I wasn't able to reproduce this exact issue locally but fixed a similar looking one in https://github.com/mtth/hdfs/commit/f4806833cd8bdd803750de7be6441ef212370e49. Can you upgrade to `2.5.1` and try again?

You can increase the verbosity of the console output with by adding this towards the top of your script:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by whg517** [comment]
hi @mtth , `2.5.1` is work fine ! 
Thanks
