### ISSUE TITLE
Avro format read-write support for external schemas

### ISSUE THREAD

**Issue by whg517** [mtth/hdfs#132]
Like [HWX Schema Registry ](https://registry-project.readthedocs.io/en/latest/), [Confluent Schema Registry](https://docs.confluent.io/current/schema-registry/index.html). supports centralized management of schema. Can you support the use of external schema when writing data? The data file contains only the data itself, and does not contain schema content. Data is read using an external schema.

This of course leads to another issue: schema version evolution. It might be complicated to do, but it would be nice to support it.

**Comment by mtth** [comment]
Do you have a use-case in mind?

Files stored on HDFS tend to be large enough that storing the schema is negligible overhead (compared to Kafka messages for example). Having the schema alongside the data has multiple benefits: single source of truth, consistency guarantees...

**Comment by whg517** [comment]
> Do you have a use-case in mind?
> 
> Files stored on HDFS tend to be large enough that storing the schema is negligible overhead (compared to Kafka messages for example). Having the schema alongside the data has multiple benefits: single source of truth, consistency guarantees...

```json
[
    {
        "ip": "172.18.80.109",

        "additional": {
            "timestamp": "2015-09-17T23:00:18.313Z",
            "message": "blahblahblah",
        }
    },
    {
        "ip": "172.18.80.112",
        "additional": {
            "microseconds": "223",
        }
    },
    {
        "ip": "172.18.80.113",
        "additional": {
            "timestamp": "2015-09-17T23:00:08.299Z",
            "message": "blahblahblah",
            "thread": "http-apr-8080-exec-1147",
        }
    }
]
```

```
Traceback (most recent call last):
  File "/home/kevin/workspaces/develop/python/StudyPython/third_library/avro_/d2.py", line 56, in <module>
    writer.write(record)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/hdfs/ext/avro/__init__.py", line 291, in __exit__
    self._writer.__exit__(*exc_info)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/hdfs/util.py", line 104, in __exit__
    raise self._err # pylint: disable=raising-bad-type
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/hdfs/util.py", line 76, in consumer
    self._consumer(data)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/hdfs/ext/avro/__init__.py", line 327, in write
    **self._writer_kwargs
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/fastavro/_write_py.py", line 691, in writer
    output.write(record)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/fastavro/_write_py.py", line 550, in write
    write_data(self.io, record, self.schema)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/fastavro/_write_py.py", line 418, in write_data
    return fn(encoder, datum, schema)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/fastavro/_write_py.py", line 361, in write_record
    name, field.get('default')), field['type'])
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/fastavro/_write_py.py", line 418, in write_data
    return fn(encoder, datum, schema)
  File "/home/kevin/.virtualenvs/StudyPython-AS8qU0JI/lib/python3.6/site-packages/fastavro/_write_py.py", line 359, in write_record
    raise ValueError('no value and no default for %s' % name)
ValueError: no value and no default for message
```

For this data, if I write directly to 'hdfs.ext.avro.avrowriter', an error will be reported due to 'hdfs.ext.avro._schemainferrer' error in my data type inference.

If you can pass in a schema, you can define the `additional` field as a [`maps`](http://avro.apache.org/docs/current/spec.html#Maps) type.

In addition, with streaming data (of course, I am mainly crawler data now), it is not possible to have all data in one file. When using date nesting as a storage strategy, problems may arise with the use of inferred schema if data sources are different and some fields of data are missing.

Use schema registry to centrally manage schema, and support version evolution and branch management.

This facilitates centralized management of schemas for data format changes.

**Comment by mtth** [comment]
Thank you for the context. This sounds useful but out of scope for this library since it isn't HDFS-specific. It is probably best handled at a higher layer, which could then be shared across various storage backends. The public APIs here should already expose enough information to implement the functionality, in particular gating writes (to avoid writing incompatible data) and orchestrating reads (to transparently unify data written with different but compatible schemas).
