### ISSUE TITLE
Connection Reset Error on a simple example

### ISSUE THREAD

**Issue by bicep** [mtth/hdfs#141]
Hello,

I am trying to upload a simple csv file using hdfscli but it seems like I am getting `ConnectionResetError`.

I am running a single node on localhost:9000. I am hoping to upload a file called daily.csv into a directory called daily. When I run:
``hdfscli upload --alias=dev /<my local directory>/daily.csv daily/``
I get this as a response:
```
ERROR	Unexpected exception.
Traceback (most recent call last):
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/urllib3/response.py", line 331, in _error_catcher
    yield
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/urllib3/response.py", line 413, in read
    data = self._fp.read(amt)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/requests/models.py", line 749, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/urllib3/response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/urllib3/response.py", line 430, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/urllib3/response.py", line 349, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/hdfs/config.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/hdfs/__main__.py", line 262, in main
    progress=progress,
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/hdfs/client.py", line 534, in upload
    hdfs_path = self.resolve(hdfs_path)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/hdfs/client.py", line 256, in resolve
    root = self._get_home_directory('/').json()['Path']
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/hdfs/client.py", line 107, in api_handler
    **self.kwargs
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/hdfs/client.py", line 214, in _request
    **kwargs
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/requests/sessions.py", line 662, in send
    r.content
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/requests/models.py", line 827, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/rogerko/miniconda3/envs/progds/lib/python3.5/site-packages/requests/models.py", line 752, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
```

I can actually upload the file using the put command with `hdfs` but I want to do it programmatically with this package. I think it's probably something really simple that I overlooked.

Here is my .hdfs.cfg:

```
[global]
default.alias = dev

[dev.alias]
url = http://localhost:9000
```

**Comment by mtth** [comment]
Hey. This looks like a connection issue but it's hard to say more from the stack trace. Which `hdfs` command did you use to successfully upload the file (in particular, which URL did you specify)? Do you get errors when you run other HdfsCLI operations, for example listing a directory or reading a file?

**Comment by bicep** [comment]
Thanks for the quick reply. 

My command is : 

`hdfs dfs -mkdir -p /user/rogerko/daily`

Followed by:

`hdfs dfs -put /Users/rogerko/yalenus/progds/hadoop/hadoop-python-mapreduce/daily.csv daily`

My core-site.xml looks like this:
```
<configuration>
<property>
<name>hadoop.tmp.dir</name>
<value>/usr/local/Cellar/hadoop/hdfs/tmp</value>
<description>A base for other temporary directories.</description>
</property>
<property>
<name>fs.default.name</name>
<value>hdfs://localhost:9000</value>
</property>
</configuration>
```

I put the daily.csv inside the daily directory successfully. So when I do `hdfs dfs -ls daily` it shows me my csv file. 

When I enter the CLI with `hdfscli  --alias=dev`, I get the same connection reset error with `CLIENT.list('daily/')`

**Comment by mtth** [comment]
Have you enabled WebHDFS? The [`examples/`](https://github.com/mtth/hdfs/tree/master/etc/hadoop) folder has a sample config with it set.

**Comment by mafeko** [comment]
Thanks @mtth for this amazing library.

I came across this old issue since I'm facing the `requests.exceptions.ChunkedEncodingError` as well from time to time in the `download` function (with files >3GB). I played around a bit using a `requests.Session` but this did not help.

I assume the root-cause lives on the server/cluster-side and just happens occasionally. 

Just in general: Would it make sense to add this `Exception` to the once which can be retried [here](https://github.com/mtth/hdfs/blob/acfe0810cd5d410783a66c19643a71db78e71b14/hdfs/client.py#L109) ?

Appreciated your feedback, happy to file a PR for this.

Best, Martin

**Comment by mafeko** [comment]
fyi @mtth 
I fixed all kind of web-request related errors using 
- `urllib3`-retry logic in the session i pass to the client
- increasing the Session-Pool to a fixed number `max_threads`
- limiting the threads in functions like `download(n_threads=max_threads)` to the same `max_threads`

With this adaptions I could get rid of those issues so far.


```python
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
import requests

max_threads = 50

session = requests.Session()

retry_strategy = Retry(
    total=10,
    connect=10,
    read=10,
    redirect=10,
    status_forcelist=[429, 500, 502, 503, 504],
    method_whitelist=["HEAD", "GET", "OPTIONS"],
)
adapter = HTTPAdapter(
    max_retries=retry_strategy, pool_connections=max_threads, pool_maxsize=max_threads,
)
session.mount("https://", adapter)
session.mount("http://", adapter)
client = KerberosClient(
    url=url,
    hostname_override=hostname_overwrite,
    root=root,
    proxy=proxy,
    timeout=timeout,
    session=session,
    **kwargs,
)

client.upload(hdfs_path=rpath, local_path=lpath, n_threads=self.max_threads)
```
