### ISSUE TITLE
How to authenticate using Kerberos delegation token file?

### ISSUE THREAD

**Issue by Nithanaroy** [mtth/hdfs#152]
```python
client = KerberosClient('http://....:50070', delegate=True)
client.list('hdfs:///')
```
produces this error
```
INFO:hdfs.client:Instantiated <KerberosClient(url='http://*****:50070')>.
INFO:hdfs.client:Listing 'hdfs:///'.
DEBUG:hdfs.client:Resolved path '/' to '/'.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): *****:50070
DEBUG:urllib3.connectionpool:http://*****:50070 "GET /webhdfs/v1/?op=GETHOMEDIRECTORY HTTP/1.1" 401 1538
DEBUG:requests_kerberos.kerberos_:handle_401(): Handling: 401
ERROR:requests_kerberos.kerberos_:generate_request_header(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/requests_kerberos/kerberos_.py", line 230, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))
ERROR:requests_kerberos.kerberos_:(('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/requests_kerberos/kerberos_.py", line 230, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))
DEBUG:requests_kerberos.kerberos_:handle_401(): returning <Response [401]>
DEBUG:requests_kerberos.kerberos_:handle_response(): returning <Response [401]>
DEBUG:requests_kerberos.kerberos_:handle_response() has seen 0 401 responses
DEBUG:requests_kerberos.kerberos_:handle_401(): Handling: 401
ERROR:requests_kerberos.kerberos_:generate_request_header(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/requests_kerberos/kerberos_.py", line 230, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))
ERROR:requests_kerberos.kerberos_:(('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/requests_kerberos/kerberos_.py", line 230, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_0)', -1765328243))
DEBUG:requests_kerberos.kerberos_:handle_401(): returning <Response [401]>
DEBUG:requests_kerberos.kerberos_:handle_response(): returning <Response [401]>
DEBUG:requests_kerberos.kerberos_:handle_response() has seen 1 401 responses
DEBUG:requests_kerberos.kerberos_:handle_response(): returning 401 <Response [401]>
ERROR:hdfs.client:b'<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>\n<title>Error 401 Authentication required. ....\n'
```
I know the location of hadoop token file. But I'm not sure how to convey this to the library. I'm able to run `hadoop fs ...` command successfully. Do I need to set any environment variables?

**Comment by Nithanaroy** [comment]
I tried using `TokenClient` by passing token file path, raw token file contents, base64 encoded contents. I get a 500 error. 

```python
with open("hdfs-delegation-token", "rb") as f:
    binary_token = f.read()
    base64_encoded_data = base64.b64encode(binary_token)
    token = base64_encoded_data.decode('utf-8')

client = hdfs.TokenClient("http://*****:50070", token=token)
client.list("hdfs:///data.txt")
```
