### ISSUE TITLE
Which Hadoop version should I use?

### ISSUE THREAD

**Issue by jesseliu77** [mtth/hdfs#29]
Hi Dear Author(s),

I would like to very thank you for your brilliant job because I just in need of the combination of pandas and HDFS.
However, when I try the run the simplest example, I've encounter such error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 396, in write
    buffersize=buffersize,
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 86, in api_handler
    **self.kwargs
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 196, in _request
    **kwargs
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x00\x00\x00|{\x08\xff\xff\xff\xff\x0f\x10\x02\x18\t")org.apache.hadoop.ipc.RPC$VersionMismatch*>Server IPC version 9 cannot communicate with client version 470\x0e:\x00@\x01',))

My hadoop version is 2.7.1, the latest one.
And I've installed spark on my server, version 1.4.1

Thanks!

**Comment by jesseliu77** [comment]
It seems that the error occurred  because I've mistaken the port. Sorry for this.
I suggest the document should contains basic WebHDFS api.
Thanks.

**Comment by mtth** [comment]
Glad to hear you solved it. Could you clarify what you mean by:

> I suggest the document should contains basic WebHDFS api.

Do you mean add code snippets for common API operations? If so, the documentation for the next release will include a couple for [reading and writing files](http://hdfscli.readthedocs.org/en/python3/quickstart.html#reading-and-writing-files) and [other operations](http://hdfscli.readthedocs.org/en/python3/quickstart.html#exploring-the-file-system).

**Comment by jesseliu77** [comment]
Yes, that's what I mean.
Keep in touch. I'll explore the fantastic lib.

**Comment by mtth** [comment]
Great!
