### ISSUE TITLE
Cant walk over dirs with spaces

### ISSUE THREAD

**Issue by XooR** [mtth/hdfs#34]
This is is REPL with "/test" dir that contains dir with spaces "dir with space". When trying to traverse that dir it tries that with "/test/dir%20with%20space" instead "/test/dir with space".
Hadoop version is: Hadoop 2.5.0-cdh5.3.6

```
>>> from hdfs import InsecureClient
>>> ic = InsecureClient("http://localhost:50070")
>>> for (path, dirs, files) in ic.walk("/test"):
...     print(dirs)
... 
[u'dir with space']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 938, in walk
    for infos in _walk(hdfs_path, s, depth):
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 932, in _walk
    for infos in _walk(path, s, depth - 1):
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 918, in _walk
    infos = self.list(dir_path, status=True)
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 887, in list
    statuses = self._list_status(hdfs_path).json()['FileStatuses']['FileStatus']
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 90, in api_handler
    **self.kwargs
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 182, in _request
    return _on_error(response)
  File "/usr/lib/python2.7/site-packages/hdfs/client.py", line 44, in _on_error
    raise HdfsError(message)
hdfs.util.HdfsError: File /test/dir%20with%20space does not exist.
```

**Comment by mtth** [comment]
Good catch, this should be fixed in the latest release (`2.0.5`). In case you'd like to know more, this is related to https://github.com/mtth/hdfs/issues/11 and https://github.com/mtth/hdfs/issues/19.
