### ISSUE TITLE
Error when using Kerberos. Ticket Expired?

### ISSUE THREAD

**Issue by sansagara2** [mtth/hdfs#49]
I'm trying to get the root HDFS directory listing. Se when i do _**CLIENT.list('/')**_ , i'm getting the following error traceback:

```
In [1]: CLIENT.list('/')
ERROR   generate_request_header(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 144, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))
ERROR   (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 144, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))
ERROR   generate_request_header(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 144, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))
ERROR   (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 144, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Ticket expired', -1765328352))
---------------------------------------------------------------------------
HdfsError                                 Traceback (most recent call last)
<ipython-input-1-b69df44579dc> in <module>()
----> 1 CLIENT.list('/')

/usr/local/lib/python3.5/site-packages/hdfs/client.py in list(self, hdfs_path, status)
    891     _logger.info('Listing %r.', hdfs_path)
    892     hdfs_path = self.resolve(hdfs_path)
--> 893     statuses = self._list_status(hdfs_path).json()['FileStatuses']['FileStatus']
    894     if len(statuses) == 1 and (
    895       not statuses[0]['pathSuffix'] or self.status(hdfs_path)['type'] == 'FILE'

/usr/local/lib/python3.5/site-packages/hdfs/client.py in api_handler(client, hdfs_path, data, strict, **params)
     90         params=params,
     91         strict=strict,
---> 92         **self.kwargs
     93       )
     94

/usr/local/lib/python3.5/site-packages/hdfs/client.py in _request(self, method, url, strict, **kwargs)
    179     )
    180     if strict and not response: # Non 2XX status code.
--> 181       return _on_error(response)
    182     else:
    183       return response

/usr/local/lib/python3.5/site-packages/hdfs/client.py in _on_error(response)
     35   """
     36   if response.status_code == 401:
---> 37     raise HdfsError('Authentication failure. Check your credentials.')
     38   try:
     39     # Cf. http://hadoop.apache.org/docs/r1.0.4/webhdfs.html#Error+Responses

HdfsError: Authentication failure. Check your credentials.

```

Right now i'm only testing this on dev, so what i have in _~/.hdfscli.cfg_ is:

```

[global]
default.alias = dev
autoload.modules = hdfs.ext.kerberos

[dev.alias]
url = http://devxx.atl.enterprise.com:50070/
client = KerberosClient

[prod.alias]
url = http://prod.namenode:port
root = /jobs/

```

What i'm doing wrong??. I Suspect it may have something to do with the user. (When i shell into the server, the username changes from mine (_latencio.site)_ to _hadoop_.

Also, i have access to Cloudera Manager to check the Kerberos Configuration.

**Comment by mtth** [comment]
Did you make sure that you have a valid ticket? Could you attach the output of `klist`?

**Comment by sansagara2** [comment]
It is as follows:

```
[hadoop@devxx ~]$ klist
Ticket cache: FILE:/tmp/krb5cc_399
Default principal: hadoop@BIGDATADEV.ENTERPRISE.COM

Valid starting     Expires            Service principal
08/09/16 16:00:33  08/10/16 16:00:33  krbtgt/BIGDATADEV.CAREERBUILDER.COM@BIGDATADEV.ENTERPRISE.COM
        renew until 08/14/16 16:00:33
08/09/16 19:24:43  08/10/16 07:24:43  host/devxx.atl.enterprise.com@
        renew until 08/14/16 16:00:33
08/09/16 19:24:43  08/10/16 07:24:43 host/devxx.atl.careerbuilder.com@BIGDATADEV.ENTERPRISE.COM
        renew until 08/14/16 16:00:33
08/09/16 19:24:43  08/10/16 16:00:33  host/devxx.atl.enterprise.com@
        renew until 08/09/16 19:24:43
08/09/16 19:24:43  08/10/16 16:00:33  host/devhd2m1.atl.enterprise.com@BIGDATADEV.ENTERPRISE.COM
        renew until 08/09/16 19:24:43
08/09/16 19:24:43  08/10/16 16:00:33  host/devxx.atl.enterprise.com@
        renew until 08/09/16 19:24:43
08/09/16 19:24:43  08/10/16 16:00:33  host/devxx.atl.enterprise.com@BIGDATADEV.ENTERPRISE.COM
        renew until 08/09/16 19:24:43
08/10/16 14:14:46  08/10/16 16:00:33  host/devxx.atl.enterprise.com@
        renew until 08/14/16 16:00:33
08/10/16 14:14:46  08/10/16 16:00:33  host/devxx.atl.enterprise.com@BIGDATADEV.ENTERPRISE.COM
        renew until 08/14/16 16:00:33
```

**Comment by sansagara2** [comment]
Ok, so i was able to get a new ticket with kinit. The issue as i mentioned, was that the cluster had a very weird way of managing ticket renewals. I talked to IT and they told me how to get a new ticket by using a keytab file in the user's home directory.

Thank you for your help. Certainly pointed in the right direction. Feel free to close.

**Comment by mtth** [comment]
Great to hear! Thanks for keeping me posted.
