### ISSUE TITLE
TypeError on mutual_auth since 2.0.14

### ISSUE THREAD

**Issue by ultrabug** [mtth/hdfs#65]
Since 2.0.14 we get this kind of error:

Is there something I'm missing ? (I don't pass any kind of kwargs on the code).

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/airflow/models.py", line 1250, in run
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.5/dist-packages/airflow/operators/python_operator.py", line 121, in execute
    condition = super(ShortCircuitOperator, self).execute(context)
  File "/usr/local/lib/python3.5/dist-packages/airflow/operators/python_operator.py", line 66, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/etc/airflow/dags/flux_chanel.zip/flux_chanel_utils/logic.py", line 77, in are_files_here
    return hook.check_for_path(hdfs_path)
  File "/usr/local/lib/python3.5/dist-packages/airflow/hooks/webhdfs_hook.py", line 57, in check_for_path
    c = self.get_conn()
  File "/usr/local/lib/python3.5/dist-packages/airflow/hooks/webhdfs_hook.py", line 39, in get_conn
    client = KerberosClient(connection_str)
  File "/usr/local/lib/python3.5/dist-packages/hdfs/ext/kerberos.py", line 121, in __init__
    session.auth = _HdfsHTTPKerberosAuth(int(max_concurrency), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hdfs/ext/kerberos.py", line 68, in __init__
    super(_HdfsHTTPKerberosAuth, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'mutual_auth'
```

**Comment by mtth** [comment]
Ah, indeed; I forgot to rename the parameter in yesterday's change. Should be fixed in `2.0.15`, thanks for bringing this up!
