### ISSUE TITLE
ConnectionResetError when writing HDFS

### ISSUE THREAD

**Issue by mohzhang** [mtth/hdfs#76]
code like:
mymodel = pickle.dumps(model) # mymodel size is about 400kb.
with client.write(path, overwrite=True) as writer:
       writer.write(mymodel)

**Comment by mtth** [comment]
Hard to help without more information; at first glance it looks more like an issue with your connection rather than something HDFS-specific. Feel free to reopen if you can provide steps to reproduce it.

**Comment by mohzhang** [comment]
This is simple reproducer. Just use your hdfs config in ./hdfscli.cfg

import pickle
from hdfs import Config

DATA_SIZE = 200 * (1 << 20)
data = 'a' * DATA_SIZE

hclient = Config('./hdfscli.cfg').get_client()
with hclient.write('/tmp/test.tmp', overwrite=True) as writer:
    writer.write(pickle.dumps(data))

**Comment by linupychiang** [comment]
Hi @mtth ,when I use the hdfs library to append content to files in hdfs, the following exception occurs, but not every time
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Below is my code:
```    try:
        hdfsClient.write(hdfs_path=path_hdfs, data=data)
    except HdfsError:
        hdfsClient.write(hdfs_path=path_hdfs, data=data, append=True)
```
The version of the hdfs library I am using is  2.5.8
Please help me, thank you very much!
