### ISSUE TITLE
Error on running provided examples - ImportError: cannot import name Config

### ISSUE THREAD

**Issue by 1605200517** [mtth/hdfs#83]
Hi, thank you for this awesome software. 

Please consider the following setup to reproduce the error.

# Dockerfile and entrypoint script 
```
FROM python:2.7
RUN apt-get -y install git
RUN python --version && pip --version
RUN pip install hdfs
WORKDIR /hdfs
RUN git clone https://github.com/mtth/hdfs.git
ADD docker-entrypoint.sh /hdfs/docker-entrypoint.sh
ENTRYPOINT /hdfs/docker-entrypoint.sh
```
Entrypoint (docker-entrypoint.sh):
```
#!/bin/bash
ls -alh
cd hdfs/examples
pip list
python json.py
python dataframe.py
sleep infinity

```

# Execution
> docker build -t test .
> docker run -it test 

# The error
Note that according to `pip list` the hdfs package is available.

```
drwxr-xr-x 1 root root 4.0K Oct 20 12:38 .
drwxr-xr-x 1 root root 4.0K Oct 20 12:38 ..
-rwxr-xr-x 1 root root   97 Oct 20 12:38 docker-entrypoint.sh
drwxr-xr-x 9 root root 4.0K Oct 20 12:23 hdfs
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2017.7.27.1)
chardet (3.0.4)
docopt (0.6.2)
hdfs (2.1.0)
idna (2.6)
pip (9.0.1)
requests (2.18.4)
setuptools (36.5.0)
six (1.11.0)
urllib3 (1.22)
virtualenv (15.1.0)
wheel (0.30.0)
Traceback (most recent call last):
  File "json.py", line 11, in <module>
    from hdfs import Config
  File "/usr/local/lib/python2.7/site-packages/hdfs/__init__.py", line 6, in <module>
    from .client import Client, InsecureClient, TokenClient
  File "/usr/local/lib/python2.7/site-packages/hdfs/client.py", line 23, in <module>
    import requests as rq
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python2.7/site-packages/requests/compat.py", line 31, in <module>
    import json
  File "/hdfs/hdfs/examples/json.py", line 11, in <module>
    from hdfs import Config
ImportError: cannot import name Config
Traceback (most recent call last):
  File "dataframe.py", line 6, in <module>
    from hdfs import Config
  File "/usr/local/lib/python2.7/site-packages/hdfs/__init__.py", line 6, in <module>
    from .client import Client, InsecureClient, TokenClient
  File "/usr/local/lib/python2.7/site-packages/hdfs/client.py", line 23, in <module>
    import requests as rq
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python2.7/site-packages/requests/compat.py", line 31, in <module>
    import json
  File "/hdfs/hdfs/examples/json.py", line 11, in <module>
    from hdfs import Config
ImportError: cannot import name Config

```

**Comment by earthquakesan** [comment]
@1605200517 hi!

it seems like "hdfs" installation is broken. Does it require any external dependencies (i.e. libs from hadoop distro) to work?

**Comment by 1605200517** [comment]
hope, @mtth can help us clarifying this; looks like a missing python dependency.

**Comment by mtth** [comment]
Hey. Looks like this was caused by the name of one of the examples colliding with another `json` module; I renamed the examples in https://github.com/mtth/hdfs/commit/86f8760d351eb2e6c43336346b4b763001e15dbd so this shouldn't be an issue anymore (don't forget to update `docker-entrypoint.sh`).

Note that for the examples to work you'll also need to add a [configuration file](http://hdfscli.readthedocs.io/en/latest/quickstart.html#configuration) with a default alias to a running HDFS cluster inside your docker image. You can then use the `HDFSCLI_CONFIG` environment variable to tell the example scripts where to find it.

**Comment by 1605200517** [comment]
thanks @mtth for updates - now with some [small adjustments](https://github.com/1605200517/docker-hadoop-spark-workbench/commit/f4b8cbec2d4c0f024220dcda2db11323358ffcd5) (further python dependencies and HDFS client profile ~/.hdfscli.cfg) it works!
