### ISSUE TITLE
OverflowError: timeout value is too large

### ISSUE THREAD

**Issue by ragerin** [mtth/hdfs#94]
Hi

When attempting to upload an entire directory of files, I receive the following output:

```python
> hdfscli upload test\ /user/ragerin/test/
ERROR   Error while uploading. Attempting cleanup.
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\hdfs\client.py", line 596, in upload
    _map_async(n_threads, _upload, fpath_tuples)
  File "c:\python36-32\lib\site-packages\hdfs\client.py", line 1122, in _map_async
    return pool.map_async(func, args).get(1 << 31)
  File "c:\python36-32\lib\multiprocessing\pool.py", line 638, in get
    self.wait(timeout)
  File "c:\python36-32\lib\multiprocessing\pool.py", line 635, in wait
    self._event.wait(timeout)
  File "c:\python36-32\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "c:\python36-32\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large
ERROR   Unexpected exception.
Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\hdfs\config.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "c:\python36-32\lib\site-packages\hdfs\__main__.py", line 260, in main
    progress=progress,
  File "c:\python36-32\lib\site-packages\hdfs\client.py", line 605, in upload
    raise err
  File "c:\python36-32\lib\site-packages\hdfs\client.py", line 596, in upload
    _map_async(n_threads, _upload, fpath_tuples)
  File "c:\python36-32\lib\site-packages\hdfs\client.py", line 1122, in _map_async
    return pool.map_async(func, args).get(1 << 31)
  File "c:\python36-32\lib\multiprocessing\pool.py", line 638, in get
    self.wait(timeout)
  File "c:\python36-32\lib\multiprocessing\pool.py", line 635, in wait
    self._event.wait(timeout)
  File "c:\python36-32\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "c:\python36-32\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large
11.1%   [ pending: 16 | downloading: 0 | complete: 2 ]
```

The client uploads part of the files with a varying degree of success. Something not even a single file, other times most of the files (though, some with partial names even).

**Comment by ragerin** [comment]
I attempted the same command, using a clean 64bit install of Python, with the exact same result.
